/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-08-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
// 15. *Conversión de Tipos*: Escribe un programa que convierta un Integer a String y viceversa.

public class Cambio {
    public Integer cambioAInt(Integer bat, String bi){
        return Integer.valueOf(bi);
    }

    public String CambioAStr(Integer bat, String bi){
        return String.valueOf(bat);
}
}