/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-08-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
// 7. *Funciones*: Crea una función que reciba dos números como parámetros y devuelva la potencia de elevar uno a otro.

public class Ejercicio7{
    public Integer potencia(Integer num1, Integer num2){
        return Math.pow(num1, num2);
    }
}