/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-11-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
// 3. *Operadores Aritméticos*: Realiza operaciones básicas de suma, resta, multiplicación y división con dos números y muestra el resultado.

public class Calculadora{
    public Integer suma (Integer num1, Integer num2){
        return num1 + num2;
    }

    public Integer resta (Integer num1, Integer num2){
        return num1 - num2;
    }

    public Integer division (Integer num1, Integer num2){
        return num1 / num2;
    }

    public Integer multi (Integer num1, Integer num2){
        return num1 * num2;
    }
}