/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-08-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
// 5. *Bucles For*: Usa un bucle for para imprimir los números del 1 al 10.

public class ImprimeNum{
    public Integer imprimir (){
        for( Integer i=1; i <11; i++){
            return i;
        }
    }
}