/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-11-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/

// 4. *Condicionales*: Escribe un programa que verifique si un número es positivo, negativo o cero.

public class Verificador{
    public String verificar(Integer num){
        if(num > 0){
            return 'Positivo';
        } else if (num == 0){
            return 'patatero'
        } else if (num<0){
            return 'minus'
        }
    }
}