/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-08-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/

// 13. *Concatenación de Strings*: Escribe un programa que tome dos String y los concatene.

public class Concat {
    public String concat (String bat, String bi){
        return bat + ' ' + bi;
    }
}