/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-08-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
// 14. *Comparación de Cadenas*: Crea un método que compare dos cadenas y devuelva si son iguales o no.

public class Compare {
    public Boolean comparar (String bat, String bi){
        if(bat == bi){
            return true;
        } else {
            return false
        }
    }
}