/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-08-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/

// 11. *Ciclo Do-While*: Implementa un bucle do-while que siga ejecutándose mientras un número sea menor a 20.


public class While {
    public Integer bucle {
        Integer i = 0;
        do {
            i++;
            return 'Hola'
        } while (i<=20);
    } 
}