/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-08-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
// 2. *Variables y Asignaciones*: Declara y asigna diferentes tipos de variables (Integer, String, Boolean) e imprime sus valores.

public with sharing class Ejercicio2 {
    public Ejercicio2() {
        Integer numero = 10;
        String texto = 'Hola';
        Boolean boleano = true;

        System.debug(numero);
        System.debug(texto);
        System.debug(boleano);
    }
}