/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-08-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
// 1. *Hello World*: Escribe un programa que imprima "Hello World" en la consola de depuración.

public with sharing class Ejercicio1 {
    public Ejercicio1() {
        System.debug('Hello World');
    }
}