/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-08-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/

// 13. *Concatenación de Strings*: Escribe un programa que tome dos String y los concatene.

public with sharing class Ejercicio13 {
    public String concatenar(String s1, String s2) {
        return s1 + s2;
    }
}